"""Georgia (GA) — forensic engineering + law firm regulatory profiles.

Sources: 13-state-gap-analysis.md batch 1 (primary_source, partial — some GA
bar/SOS pages were Cloudflare-blocked).
Confidence: forensic = primary_source; legal = established_knowledge.
Notable: GA follows Daubert; firm COA required (O.C.G.A. §43-15-13).
"""
from __future__ import annotations

from . import ForensicProfile, LegalProfile, MedicalProfile

FORENSIC = ForensicProfile(
    state="GA",
    state_name="Georgia",
    board_name="Georgia State Board of Registration for Professional Engineers and Land Surveyors",
    board_url="https://sos.ga.gov/georgia-consumer-protection/boards/registration-professional-engineers-and-land-surveyors",
    governing_statute="O.C.G.A. Chapter 15 of Title 43 (Professional Engineers and Land Surveyors)",
    statute_url="https://law.georgia.gov/paraphrase/?title=43&chapter=15",
    firm_coa_required=True,
    firm_coa_citation="O.C.G.A. §43-15-13 (Certificate of Authorization for firms)",
    firm_coa_fee="",
    electronic_seal_authorized=True,
    electronic_seal_citation="Georgia Electronic Records and Signatures Act (O.C.G.A. §10-12-1 et seq.)",
    admissibility_standard="daubert",
    admissibility_citation="GA follows Daubert (general acceptance of reliable scientific evidence)",
    pdh_hours=30,
    pdh_cycle_years=2,
    pdh_ethics_hours=2,
    pdh_citation="Ga. Comp. R. & Regs. r. 180-7 (continuing education; 30 PDH/biennium incl. 2 ethics)",
    forensic_specific_rules="None",
    confidence="primary_source",
)


LEGAL = LegalProfile(
    state="GA",
    state_name="Georgia",
    bar_name="State Bar of Georgia (unified, mandatory)",
    bar_url="https://www.gabar.org",
    governing_rules="Georgia Rules of Professional Conduct",
    rules_url="https://www.gabar.org/forthepublic/lawyerregulation/georgiarulesofprofessionalconduct.cfm",
    cle_required=True,
    cle_hours=12,
    cle_cycle_years=1,
    cle_ethics_hours=1,
    cle_citation="GA CLE rules (12 credits/yr incl. ethics + trial practice)",
    advertising_filing_required=False,
    advertising_filing_citation="",
    advertising_filing_authority="",
    data_security_tier="breach_notification_only",
    data_security_citation="O.C.G.A. §10-1-912 (GA Identity Theft Protection Act; breach notification)",
    iolta_required=True,
    iolta_authority="Georgia Bar Foundation / GA IOLTA program",
    upl_statute="O.C.G.A. §15-19-9 (unauthorized practice of law)",
    mdp_prohibited=True,
    confidence="established_knowledge",
)

MEDICAL = MedicalProfile(
    state="GA",
    state_name="Georgia",
    board_name="Composite State Board of Medical Examiners",
    board_url="https://sos.ga.gov/georgia-consumer-services/composite-state-board-medical-examiners",
    board_parent_agency="GA Secretary of State, Professional Licensing Boards",
    governing_statute="O.C.G.A. Title 43, Ch. 34",
    statute_url="https://www.legis.ga.gov/legislation/ocga (Cloudflare-blocked — verify when web tools restored)",
    license_cycle_years=2,
    license_renewal_note="biennial",
    imlc_member=True,
    imlc_citation="O.C.G.A. — IMLC member (ESTABLISHED — verify)",
    np_supervision_model="supervision",
    np_supervision_citation="O.C.G.A. §43-34-25 — NP requires protocol/delegation (ESTABLISHED — verify)",
    corporate_practice_prohibited=True,
    corporate_practice_citation="Corporate practice doctrine (ESTABLISHED — verify)",
    upl_statute="O.C.G.A. §43-34-20 (unlicensed practice — misdemeanor/felony) (ESTABLISHED — verify)",
    record_retention_adult_years=10,
    record_retention_minor_years=10,
    record_retention_minor_rule="10 years from last visit (ESTABLISHED — verify)",
    record_retention_citation="O.C.G.A. §43-34-37 (ESTABLISHED — verify)",
    patient_access_days=0,
    patient_access_citation="ESTABLISHED — verify (HIPAA floor applies)",
    telemedicine_requirement="no_prior_exam",
    telemedicine_prior_in_person=False,
    telemedicine_citation="O.C.G.A. §43-34-31.1 (ESTABLISHED — verify)",
    cross_state_practice_allowed=False,
    cross_state_citation="ESTABLISHED — verify",
    written_consent_procedures="ESTABLISHED — verify",
    telemedicine_consent_documented=True,
    advertising_filing_required=False,
    advertising_restrictions="ESTABLISHED — verify",
    data_security_tier="breach_notification_only",
    data_security_citation="O.C.G.A. §39-1-2 (ESTABLISHED — verify)",
    breach_notification_days=60,
    breach_notification_citation="GA breach law (ESTABLISHED — verify; likely 60 days)",
    cme_required=True,
    cme_hours=40,
    cme_cycle_years=2,
    cme_mandatory_topics=(),
    cme_topic_cycle_years=0,
    cme_citation="40 hrs/biennium (ESTABLISHED — verify)",
    pmp_query_required=True,
    pmp_citation="O.C.G.A. §16-13-64 (PDMP) (ESTABLISHED — verify)",
    initial_opioid_rx_limit_days=0,
    initial_opioid_rx_citation="ESTABLISHED — verify",
    mat_buprenorphine_permitted=True,
    mat_citation="DEA-registered (ESTABLISHED — verify)",
    minor_consent_services=("reproductive", "sti", "substance_use", "behavioral_health"),
    minor_parent_access_restricted=True,
    minor_consent_citation="O.C.G.A. §31-9-2 (ESTABLISHED — verify)",
    confidence="established_knowledge",
)
