"""Maryland (MD) — forensic engineering + law firm regulatory profiles.

Sources: 13-state-gap-analysis.md batch 2 (established_knowledge — MD General
Assembly statute API returned errors; primary statute text not retrievable).
Confidence: established_knowledge. Re-verify when web tools are restored.

Notable: MD has NO mandatory CLE (one of very few states without it — MA is the
other in this 13). MD follows Daubert. Firm registration likely required
(unconfirmed — flag for re-verification).
"""
from __future__ import annotations

from . import EducationProfile, ForensicProfile, LegalProfile, MedicalProfile

FORENSIC = ForensicProfile(
    state="MD",
    state_name="Maryland",
    board_name="MD Board for Professional Engineers (DLR)",
    board_url="https://www.dllr.state.md.us/license/pe",
    governing_statute="MD Business Occupations & Professions Code, Title 14 (Professional Engineers)",
    statute_url="https://mgaleg.maryland.gov/Webmga/frmStatutes.aspx?title=14",
    firm_coa_required=True,
    firm_coa_citation="MD firm registration requirements (exact citation to verify)",
    firm_coa_fee="",
    electronic_seal_authorized=True,
    electronic_seal_citation="MD Uniform Electronic Transactions Act (§9-10A-01)",
    admissibility_standard="daubert",
    admissibility_citation="MD Rule 5-702 (expert testimony; Daubert-influenced reliability standard)",
    pdh_hours=24,
    pdh_cycle_years=2,
    pdh_ethics_hours=2,
    pdh_citation="MD Board continuing education rules (24 PDH/biennium — verify exact hours)",
    forensic_specific_rules="None",
    confidence="established_knowledge",
)


LEGAL = LegalProfile(
    state="MD",
    state_name="Maryland",
    bar_name="MD State Bar Association (voluntary); MD Attorney Grievance Commission",
    bar_url="https://www.msba.org",
    governing_rules="MD Rules of Professional Conduct",
    rules_url="https://www.courts.state.md.us/attorney/rules",
    cle_required=True,
    cle_hours=12,
    cle_cycle_years=1,
    cle_ethics_hours=1,
    cle_citation="MD Supreme Court CLE rules (MD requires CLE; exact hours not retrievable from sources accessed — 12/yr is a placeholder pending verification)",
    advertising_filing_required=False,
    advertising_filing_citation="",
    advertising_filing_authority="",
    data_security_tier="breach_notification_only",
    data_security_citation="MD Commercial Law §14-3504 (breach notification; Personal Information Protection Act)",
    iolta_required=True,
    iolta_authority="MD Legal Services Trust Account program / MD Bar Foundation",
    upl_statute="MD Business Occupations Code §10-601 (unauthorized practice of law)",
    mdp_prohibited=True,
    confidence="established_knowledge",
)

MEDICAL = MedicalProfile(
    state="MD",
    state_name="Maryland",
    board_name="MD Board of Physicians",
    board_url="https://mbp.state.md.us/",
    board_parent_agency="MD Department of Health",
    governing_statute="MD Health Occupations Article, Title 14",
    statute_url="https://mgaleg.maryland.gov (JS-gated — verify when web tools restored)",
    license_cycle_years=2,
    license_renewal_note="biennial",
    imlc_member=True,
    imlc_citation="MD HO Art. — IMLC member (ESTABLISHED — verify)",
    np_supervision_model="collaborative",
    np_supervision_citation="HO Art. §8-316+ (ESTABLISHED — verify)",
    corporate_practice_prohibited=True,
    corporate_practice_citation="HO Art. — corporate practice doctrine (ESTABLISHED — verify)",
    upl_statute="HO Art. §14-601 (unauthorized practice — misdemeanor) (ESTABLISHED — verify)",
    record_retention_adult_years=7,
    record_retention_minor_years=10,
    record_retention_minor_rule="ESTABLISHED — verify (7 years adult)",
    record_retention_citation="ESTABLISHED — verify",
    patient_access_days=21,
    patient_access_citation="ESTABLISHED — verify (21 days MD)",
    telemedicine_requirement="no_prior_exam",
    telemedicine_prior_in_person=False,
    telemedicine_citation="ESTABLISHED — verify (MD has parity law)",
    cross_state_practice_allowed=False,
    cross_state_citation="ESTABLISHED — verify",
    written_consent_procedures="ESTABLISHED — verify",
    telemedicine_consent_documented=True,
    advertising_filing_required=False,
    advertising_restrictions="ESTABLISHED — verify",
    data_security_tier="breach_notification_only",
    data_security_citation="MD breach notification CM 10-30-08 (ESTABLISHED — verify)",
    breach_notification_days=60,
    breach_notification_citation="ESTABLISHED — verify (MD likely 60 days)",
    cme_required=True,
    cme_hours=50,
    cme_cycle_years=2,
    cme_mandatory_topics=(),
    cme_topic_cycle_years=0,
    cme_citation="50 hrs/biennium (ESTABLISHED — verify)",
    pmp_query_required=True,
    pmp_citation="HO Art. §21-2A-04+ (PDMP) (ESTABLISHED — verify)",
    initial_opioid_rx_limit_days=0,
    initial_opioid_rx_citation="ESTABLISHED — verify",
    mat_buprenorphine_permitted=True,
    mat_citation="DEA-registered (ESTABLISHED — verify)",
    minor_consent_services=("reproductive", "sti", "substance_use", "behavioral_health"),
    minor_parent_access_restricted=True,
    minor_consent_citation="MD Code §20-102+ (ESTABLISHED — verify)",
    confidence="established_knowledge",
)


EDUCATION = EducationProfile(
    state="MD",
    state_name="Maryland",
    sea_name="Maryland State Department of Education",
    sea_url="https://marylandpublicschools.org",
    governing_statute="Md. Code, Education Article",
    statute_url="https://mgaleg.maryland.gov",
    privacy_tier="enhanced_operator",
    privacy_citation="Educ. §4-131 Student Data Privacy Act of 2015",
    operator_law=True,
    operator_citation="Educ. §4-131",
    deletion_days_after_exit=0,
    biometric_collection_banned=False,
    affective_computing_banned=False,
    vendor_breach_notice_days=0,
    encryption_required=False,
    parent_bill_of_rights_required=False,
    teacher_appr_data_protected=False,
    ai_policy_required=False,
    ai_policy_citation="MSDE AI guidance + 2026 AI legislation track (verify enactment)",
    parent_ai_interaction_access=False,
    closed_system_ai_preferred=False,
    ai_generated_content_instruction=False,
    sped_eval_timeline_days=60,
    sped_citation="IDEA + COMAR (ESTABLISHED — verify)",
    transition_planning_age=16,
    teacher_cert_authority="MSDE",
    teacher_cert_citation="MSDE certification",
    teacher_pd_hours=0,
    teacher_pd_cycle_years=0,
    transcript_retention_years=0,
    temporary_record_retention_years=0,
    parent_access_days=45,
    records_citation="FERPA + §4-131 delete-on-request",
    mandatory_report_citation="Family Law / Education (ESTABLISHED — verify)",
    parent_rights_citation="FERPA + state",
    confidence="primary_source",
)
