"""Ohio (OH) — forensic engineering + law firm regulatory profiles.

Sources: 13-state-gap-analysis.md batch 2 (primary_source).
Confidence: primary_source.
Notable: OH follows Daubert; firm registration required (ORC §4733.16);
OH explicitly authorizes digital seals with specific criteria (§4733.14).
"""
from __future__ import annotations

from . import EducationProfile, ForensicProfile, LegalProfile, MedicalProfile

FORENSIC = ForensicProfile(
    state="OH",
    state_name="Ohio",
    board_name="OH State Board of Registration for Professional Engineers and Land Surveyors",
    board_url="https://peps.ohio.gov",
    governing_statute="OH Revised Code Chapter 4733 (Professional Engineers and Land Surveyors)",
    statute_url="https://codes.ohio.gov/orc/4733",
    firm_coa_required=True,
    firm_coa_citation="ORC §4733.16 (firm registration required)",
    firm_coa_fee="",
    electronic_seal_authorized=True,
    electronic_seal_citation="ORC §4733.14 (digital seals: unique, verifiable, sole control, document-linked)",
    admissibility_standard="daubert",
    admissibility_citation="State v. Steadman, 2015-Ohio-4919 (OH applies Daubert)",
    pdh_hours=30,
    pdh_cycle_years=2,
    pdh_ethics_hours=2,
    pdh_citation="OAC 4733-13 (continuing education; 30 PDH/biennium incl. 2 ethics)",
    forensic_specific_rules="None",
    confidence="primary_source",
)


LEGAL = LegalProfile(
    state="OH",
    state_name="Ohio",
    bar_name="OH State Bar Association (voluntary); Office of Disciplinary Counsel",
    bar_url="https://www.ohiobar.org",
    governing_rules="Ohio Rules of Professional Conduct",
    rules_url="https://www.supremecourt.ohio.gov/Boards/OPC/rules/",
    cle_required=True,
    cle_hours=24,
    cle_cycle_years=2,
    cle_ethics_hours=2,
    cle_citation="OH Gov. Bar R. X (CLE; 24 credits/2yr incl. 2.5 ethics/yr)",
    advertising_filing_required=False,
    advertising_filing_citation="",
    advertising_filing_authority="",
    data_security_tier="breach_notification_only",
    data_security_citation="ORC §1347.12 (breach notification; OH Personal Information Systems)",
    iolta_required=True,
    iolta_authority="OH IOLTA / Ohio State Bar Foundation",
    upl_statute="ORC §4705 (unauthorized practice of law)",
    mdp_prohibited=True,
    confidence="primary_source",
)

MEDICAL = MedicalProfile(
    state="OH",
    state_name="Ohio",
    board_name="OH State Medical Board",
    board_url="https://med.ohio.gov/",
    board_parent_agency="OH Department of Health (independent board)",
    governing_statute="ORC Ch. 4731",
    statute_url="https://codes.ohio.gov/ohio-revised-code/chapter-4731",
    license_cycle_years=2,
    license_renewal_note="biennial (2 yr from issuance)",
    imlc_member=True,
    imlc_citation="ORC — IMLC member (ESTABLISHED — verify section)",
    np_supervision_model="collaborative",
    np_supervision_citation="ORC §4723.01+ (ESTABLISHED — verify; OH NPs have Standard Care Arrangement)",
    corporate_practice_prohibited=True,
    corporate_practice_citation="ORC §4731.22 (ESTABLISHED — verify)",
    upl_statute="ORC §4731.34 (unauthorized practice — misdemeanor) (ESTABLISHED — verify)",
    record_retention_adult_years=7,
    record_retention_minor_years=10,
    record_retention_minor_rule="7 years adult; until age 21 for minors (ESTABLISHED — verify)",
    record_retention_citation="ESTABLISHED — verify",
    patient_access_days=0,
    patient_access_citation="ESTABLISHED — verify (HIPAA floor)",
    telemedicine_requirement="no_prior_exam",
    telemedicine_prior_in_person=False,
    telemedicine_citation="ESTABLISHED — verify (OH telemedicine rules)",
    cross_state_practice_allowed=False,
    cross_state_citation="ESTABLISHED — verify",
    written_consent_procedures="ESTABLISHED — verify",
    telemedicine_consent_documented=True,
    advertising_filing_required=False,
    advertising_restrictions="ESTABLISHED — verify",
    data_security_tier="breach_notification_only",
    data_security_citation="OH breach notification §1349.19 (ESTABLISHED — verify)",
    breach_notification_days=60,
    breach_notification_citation="ESTABLISHED — verify (OH likely 45-60 days)",
    cme_required=True,
    cme_hours=100,
    cme_cycle_years=2,
    cme_mandatory_topics=("opioid_education",),
    cme_topic_cycle_years=0,
    cme_citation="ESTABLISHED — verify (100 hrs/biennium incl. opioid CME)",
    pmp_query_required=True,
    pmp_citation="ORC §4729.74+ (OARRS) (ESTABLISHED — verify)",
    initial_opioid_rx_limit_days=7,
    initial_opioid_rx_citation="ORC §4731.75+ (7-day acute opioid Rx limit) (ESTABLISHED — verify)",
    mat_buprenorphine_permitted=True,
    mat_citation="DEA-registered (ESTABLISHED — verify)",
    minor_consent_services=("reproductive", "sti", "substance_use", "behavioral_health"),
    minor_parent_access_restricted=True,
    minor_consent_citation="ESTABLISHED — verify",
    confidence="primary_source",
)


EDUCATION = EducationProfile(
    state="OH",
    state_name="Ohio",
    sea_name="Ohio Department of Education and Workforce",
    sea_url="https://education.ohio.gov",
    governing_statute="ORC Title 33",
    statute_url="https://codes.ohio.gov",
    privacy_tier="enhanced_operator",
    privacy_citation="ORC §§3319.325–.327 (SB 29)",
    operator_law=True,
    operator_citation="ORC §§3319.325–.327",
    deletion_days_after_exit=90,
    biometric_collection_banned=False,
    affective_computing_banned=False,
    vendor_breach_notice_days=0,
    encryption_required=False,
    parent_bill_of_rights_required=False,
    teacher_appr_data_protected=False,
    ai_policy_required=True,
    ai_policy_citation="ORC §3301.24 — district AI policy by July 1, 2026",
    parent_ai_interaction_access=False,
    closed_system_ai_preferred=False,
    ai_generated_content_instruction=False,
    sped_eval_timeline_days=60,
    sped_citation="OAC 3301-51 (ESTABLISHED — verify)",
    transition_planning_age=14,
    teacher_cert_authority="ODEW",
    teacher_cert_citation="ODE licensure",
    teacher_pd_hours=0,
    teacher_pd_cycle_years=0,
    transcript_retention_years=0,
    temporary_record_retention_years=0,
    parent_access_days=45,
    records_citation="ORC §§3319.325–.327 (district property; 90-day return/destroy)",
    mandatory_report_citation="ORC §2151.421",
    parent_rights_citation="FERPA + annual tech-provider notice (SB 29)",
    confidence="primary_source",
)
