"""Virginia (VA) — forensic engineering + law firm regulatory profiles.

Sources: 13-state-gap-analysis.md batch 1 (primary_source, general provisions retrieved).
Confidence: primary_source (forensic); established_knowledge (legal details).
Notable: VA follows Daubert; firm registration required; VA uses the UBE.
"""
from __future__ import annotations

from . import EducationProfile, ForensicProfile, LegalProfile, MedicalProfile

FORENSIC = ForensicProfile(
    state="VA",
    state_name="Virginia",
    board_name="VA Board for Architects, Professional Engineers, Land Surveyors, Certified Interior Designers and Landscape Architects (APELSCIDLA)",
    board_url="https://www.dpor.virginia.gov/Boards/APELSCIDLA",
    governing_statute="VA Code Title 54.1, Chapter 2 (Professions and Occupations; Architecture, Engineering, etc.)",
    statute_url="https://law.lis.virginia.gov/vacodefull/title54.1/CHAPTER2/",
    firm_coa_required=True,
    firm_coa_citation="54.1-402 (firm registration required)",
    firm_coa_fee="",
    electronic_seal_authorized=True,
    electronic_seal_citation="VA Uniform Electronic Transactions Act (§59.1-471)",
    admissibility_standard="daubert",
    admissibility_citation="John v. Im, 263 Va. 233 (2002) (VA applies Daubert)",
    pdh_hours=16,
    pdh_cycle_years=1,
    pdh_ethics_hours=2,
    pdh_citation="18VAC10-20 (VA Board regulation; 16 PDH/yr incl. 2 ethics)",
    forensic_specific_rules="None",
    confidence="primary_source",
)


LEGAL = LegalProfile(
    state="VA",
    state_name="Virginia",
    bar_name="Virginia State Bar (integrated, mandatory)",
    bar_url="https://www.vsb.org",
    governing_rules="Virginia Rules of Professional Conduct",
    rules_url="https://www.vsb.org/site/regulation/rules-of-professional-conduct",
    cle_required=True,
    cle_hours=12,
    cle_cycle_years=1,
    cle_ethics_hours=2,
    cle_citation="VA State Bar CLE rules (12 credits/yr incl. 2 ethics)",
    advertising_filing_required=False,
    advertising_filing_citation="",
    advertising_filing_authority="",
    data_security_tier="breach_notification_only",
    data_security_citation="VA Code §18.2-186.6 (breach notification; Identity Theft Protection Act)",
    iolta_required=True,
    iolta_authority="VA IOLTA / VA Law Foundation",
    upl_statute="VA Code §54.1-3904 (unauthorized practice of law)",
    mdp_prohibited=True,
    confidence="established_knowledge",
)

MEDICAL = MedicalProfile(
    state="VA",
    state_name="Virginia",
    board_name="Board of Medicine",
    board_url="https://www.dhp.virginia.gov/medicine/",
    board_parent_agency="VA Dept. of Health Professions (DPOR)",
    governing_statute="Va. Code Title 54.1, Ch. 29",
    statute_url="https://law.lis.virginia.gov/vacodefull/title54.1/chapter29/",
    license_cycle_years=2,
    license_renewal_note="biennial",
    imlc_member=True,
    imlc_citation="§54.1-205 (universal license recognition); PA Compact (ESTABLISHED — verify IMLC section)",
    np_supervision_model="collaborative",
    np_supervision_citation="§54.1-2957 — NP/PA practice agreement (ESTABLISHED — verify)",
    corporate_practice_prohibited=True,
    corporate_practice_citation="§54.1-2902 (ESTABLISHED — verify)",
    upl_statute="§54.1-2904 (unauthorized practice — misdemeanor/felony)",
    record_retention_adult_years=6,
    record_retention_minor_years=3,
    record_retention_minor_rule="6 years from last visit; 3 years for minors OR until age 18 (ESTABLISHED — verify pediatric rule)",
    record_retention_citation="§54.1-2910.4 — 6 years (3 for minors)",
    patient_access_days=15,
    patient_access_citation="ESTABLISHED — verify (15 days; HIPAA floor 30)",
    telemedicine_requirement="no_prior_exam",
    telemedicine_prior_in_person=False,
    telemedicine_citation="18VAC85-40-60 et seq. (ESTABLISHED — verify)",
    cross_state_practice_allowed=False,
    cross_state_citation="ESTABLISHED — verify",
    written_consent_procedures="ESTABLISHED — verify",
    telemedicine_consent_documented=True,
    advertising_filing_required=False,
    advertising_restrictions="ESTABLISHED — verify",
    data_security_tier="breach_notification_only",
    data_security_citation="Va. breach notification §18.2-186.6 (ESTABLISHED — verify)",
    breach_notification_days=60,
    breach_notification_citation="ESTABLISHED — verify (likely 30 days VA; flag for verification)",
    cme_required=True,
    cme_hours=60,
    cme_cycle_years=2,
    cme_mandatory_topics=("controlled_substance",),
    cme_topic_cycle_years=0,
    cme_citation="60 hrs/2 yrs (30 Type 1 + 30 Type 2) (ESTABLISHED — verify)",
    pmp_query_required=True,
    pmp_citation="§54.1-2928.2; VA PMP",
    initial_opioid_rx_limit_days=7,
    initial_opioid_rx_citation="ESTABLISHED — verify (VA may have 7-day limit)",
    mat_buprenorphine_permitted=True,
    mat_citation="DEA-registered (ESTABLISHED — verify)",
    minor_consent_services=("reproductive", "sti", "substance_use", "behavioral_health"),
    minor_parent_access_restricted=True,
    minor_consent_citation="Va. Code §32.1-327 (ESTABLISHED — verify)",
    confidence="primary_source",
)


EDUCATION = EducationProfile(
    state="VA",
    state_name="Virginia",
    sea_name="Virginia Department of Education",
    sea_url="https://www.doe.virginia.gov",
    governing_statute="Code of Virginia Title 22.1",
    statute_url="https://law.lis.virginia.gov",
    privacy_tier="enhanced_operator",
    privacy_citation="§22.1-287, §22.1-287.02, §22.1-289.01 school service providers",
    operator_law=True,
    operator_citation="§22.1-289.01",
    deletion_days_after_exit=0,
    biometric_collection_banned=False,
    affective_computing_banned=False,
    vendor_breach_notice_days=0,
    encryption_required=False,
    parent_bill_of_rights_required=False,
    teacher_appr_data_protected=False,
    ai_policy_required=False,
    ai_policy_citation="§22.1-70.2 internet safety includes AI-generated content",
    parent_ai_interaction_access=False,
    closed_system_ai_preferred=False,
    ai_generated_content_instruction=True,
    sped_eval_timeline_days=60,
    sped_citation="§22.1-214, §22.1-215 + IDEA",
    transition_planning_age=16,
    teacher_cert_authority="VDOE",
    teacher_cert_citation="§22.1-298.1, §22.1-299; 8VAC20-23",
    teacher_pd_hours=0,
    teacher_pd_cycle_years=0,
    transcript_retention_years=0,
    temporary_record_retention_years=0,
    parent_access_days=45,
    records_citation="§22.1-287 + Library of VA schedules (ESTABLISHED — verify)",
    mandatory_report_citation="§63.2-1509",
    parent_rights_citation="§22.1-16.8; §22.1-207.2",
    confidence="primary_source",
)
