"""West Virginia (WV) — forensic engineering + law firm regulatory profiles.

Sources: 13-state-gap-analysis.md batch 2 (primary_source).
Confidence: primary_source.
Notable: WV follows Daubert; firm registration required (§30-13-17);
WV explicitly REJECTS facsimile signatures (must be wet/original seal).
"""
from __future__ import annotations

from . import ForensicProfile, LegalProfile, MedicalProfile

FORENSIC = ForensicProfile(
    state="WV",
    state_name="West Virginia",
    board_name="WV State Board of Registration for Professional Engineers",
    board_url="https://wvpe.org",
    governing_statute="WV Code, Chapter 30, Article 13 (Professional Engineers)",
    statute_url="http://www.wvlegislature.gov/WVCODE/Code/30-13/master.html",
    firm_coa_required=True,
    firm_coa_citation="§30-13-17 (firm Certificate of Authorization)",
    firm_coa_fee="",
    electronic_seal_authorized=True,
    electronic_seal_citation="WV Electronic Transactions Act (WVC §39-5-1); note: WV rejects facsimile signatures — wet/original seal required",
    admissibility_standard="daubert",
    admissibility_citation="Wilt v. Buracker, 963 F.Supp. 1160 (S.D.W.Va. 1997); WV applies Daubert",
    pdh_hours=15,
    pdh_cycle_years=1,
    pdh_ethics_hours=2,
    pdh_citation="WV Board Rule 23CSR1 (continuing education; hours set by board)",
    forensic_specific_rules="None",
    confidence="primary_source",
)


LEGAL = LegalProfile(
    state="WV",
    state_name="West Virginia",
    bar_name="WV State Bar (integrated, mandatory)",
    bar_url="https://www.wvbar.org",
    governing_rules="WV Rules of Professional Conduct",
    rules_url="https://www.wvbar.org/rules-of-professional-conduct/",
    cle_required=True,
    cle_hours=24,
    cle_cycle_years=2,
    cle_ethics_hours=3,
    cle_citation="WV State Bar CLE rules (24 credits/2yr incl. 3 ethics)",
    advertising_filing_required=False,
    advertising_filing_citation="",
    advertising_filing_authority="",
    data_security_tier="breach_notification_only",
    data_security_citation="WVC §46A-2A-10 (breach notification; WV Consumer Credit Protection Act)",
    iolta_required=True,
    iolta_authority="WV State Bar IOLTA / WV Law Foundation",
    upl_statute="WVC §30-2-4 (unauthorized practice of law)",
    mdp_prohibited=True,
    confidence="primary_source",
)

MEDICAL = MedicalProfile(
    state="WV",
    state_name="West Virginia",
    board_name="WV Board of Medicine (allopathic) + WV Board of Osteopathic Medicine",
    board_url="https://www.wvbom.wv.gov/",
    board_parent_agency="WV Department of Health",
    governing_statute="WV Code Ch. 30, Art. 3",
    statute_url="https://code.wvlegislature.gov/chapter/30/Article-3/",
    license_cycle_years=2,
    license_renewal_note="biennial",
    imlc_member=True,
    imlc_citation="WV Code — IMLC member (ESTABLISHED — verify section)",
    np_supervision_model="collaborative",
    np_supervision_citation="WV Code §30-7-1+ (ESTABLISHED — verify)",
    corporate_practice_prohibited=True,
    corporate_practice_citation="WV Code — COA required for corporations (§30-3-15 ESTABLISHED)",
    upl_statute="WV Code §30-3-15 (unauthorized practice — misdemeanor/felony)",
    record_retention_adult_years=7,
    record_retention_minor_years=10,
    record_retention_minor_rule="ESTABLISHED — verify (7 years adult)",
    record_retention_citation="ESTABLISHED — verify (WV general records statute)",
    patient_access_days=0,
    patient_access_citation="ESTABLISHED — verify (HIPAA floor)",
    telemedicine_requirement="no_prior_exam",
    telemedicine_prior_in_person=False,
    telemedicine_citation="WV Code §16-5DD (telehealth) (ESTABLISHED — verify)",
    cross_state_practice_allowed=False,
    cross_state_citation="ESTABLISHED — verify",
    written_consent_procedures="ESTABLISHED — verify",
    telemedicine_consent_documented=True,
    advertising_filing_required=False,
    advertising_restrictions="ESTABLISHED — verify",
    data_security_tier="breach_notification_only",
    data_security_citation="WV breach notification §46A-2A-100+ (ESTABLISHED — verify)",
    breach_notification_days=60,
    breach_notification_citation="ESTABLISHED — verify",
    cme_required=True,
    cme_hours=50,
    cme_cycle_years=2,
    cme_mandatory_topics=("controlled_substance",),
    cme_topic_cycle_years=0,
    cme_citation="§30-3-12 — 50 CME/biennium incl. controlled-substance CME (ESTABLISHED — verify opioid-specific)",
    pmp_query_required=True,
    pmp_citation="WV Code — PDMP (ESTABLISHED — verify)",
    initial_opioid_rx_limit_days=0,
    initial_opioid_rx_citation="ESTABLISHED — verify",
    mat_buprenorphine_permitted=True,
    mat_citation="DEA-registered (ESTABLISHED — verify)",
    minor_consent_services=("reproductive", "sti", "substance_use", "behavioral_health"),
    minor_parent_access_restricted=True,
    minor_consent_citation="ESTABLISHED — verify",
    confidence="primary_source",
)
